[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-pure"
version = "2.1.0"
description = "Implements a dummy function (get_fortytwo.DummyClass.get_42()) in rust"
readme = "Readme.md"
edition = "2018"

[package.metadata.maturin.scripts]
get_42 = "pyo3_pure:DummyClass.get_42"

[dependencies]
# This is temporary until https://github.com/PyO3/pyo3/pull/1152 is merged
pyo3 = { git = "https://github.com/PyO3/pyo3", branch = "abi3", deafult-features = false, features = ["extension-module", "macros"] }

[lib]
name = "pyo3_pure"
crate-type = ["cdylib"]
